### PR TITLE
Frontend create product detail screen

### LINKED ISSUE #39: Create Product detail screen

### LINKED ISSUE #40: Create Product review screen

### PR DESCRIPTION
**Pull request by marmontm**
This will close #39 .  
This will close #40 .
  
> Note for **ProductDetail screen**:  
> I have a small problem with the popup after added the product, so user can still add/remove product by clicking the "+" button, but no popup will appear for now.  
> I am working on it, but it won't prevent you to test the app. Thanks bro :)

**1. Product Detail screen:**
screen shot 2018-04-14 at 15 09 51
> Note: The spaces above and below the TopReview are due to flexbox, but once you will include it between your header and navbar, it will adjust and look better !
  
  
**2. Product Detail Reviews screen:**
screen shot 2018-04-14 at 15 10 04

### CODE REVIEW

**Comment by jeremydang** [comment]
Good job ! Only small changes: The border of add product button should be 1px width. 

I will wait for your popup fix then I will merge them altogether.

**Comment by marmontm** [comment]
Yes, the thing is the popup appears when one of my variable in the state is "false" instead of "true", so I have to find where is this come from. And for the "+" button that's because I used a material icon, but I find an other way to have a thinner border :)

**Comment by jeremydang** [comment]
For the styling of the button, you can take a look at Product.js in Common folder, I have already implemented the add product button there. 
For the popup, you do not have to implement the popup appear only once because this will depend on the database for the user. So for now it can be every time the user click add/remove button, the popup always appear.

**Comment by marmontm** [comment]
Got it. Update is coming..

**Comment by marmontm** [comment]
Ok, popup is fixed, and add button also. See:  

screen shot 2018-04-14 at 19 39 39
screen shot 2018-04-14 at 19 39 45
screen shot 2018-04-14 at 19 39 50

**Pull request merged**
