### PR TITLE
Add Friends Component

### LINKED ISSUE #45: Create Friends Component

### PR DESCRIPTION
**Pull request by rwbarkeriv**
This will close #45 
screen shot 2018-03-31 at 9 42 21 pm

### CODE REVIEW

**Comment by rwbarkeriv** [comment]
There is still logic mixed with the ui from the List. Couldnt figure it out haha i can fix it later though

**Comment by jeremydang** [comment]
You can create a ProfileScreenContainer that will only render the friend component, but then later you will use this class to also render other components as well. Then use this one to supply data to your Friend Component.

**Comment by rwbarkeriv** [comment]
Ok sounds good!:)

**Comment by rwbarkeriv** [comment]
Thanks!

**Comment by jeremydang** [comment]
In detail it should be: create your Friend component that contains only avatar and name, then FriendContainer component (stateful conponent) that renders a list of friend component together with '28 friends and followers', give the number 28 placeholder as well (so that later we can change the number easily). Then on your full ProfileScreenContainer, renders this FriendContainer together with other things.

**Comment by jeremydang** [comment]
Didn't notice that you use <List> to render items, then just ignore the previous comment :)))

**Comment by rwbarkeriv** [comment]
hey what do you mean by placeholder ? like make a state variable and assign the value through that until the database is connected?

**Comment by jeremydang** [comment]
Yes it is like that

**Comment by rwbarkeriv** [comment]
Hey it should all be fixed now @jeremydang

**Comment by rwbarkeriv** [comment]
hopefully haha

**Comment by rwbarkeriv** [comment]
I wasnt able to set the variable to list.length however so if you know let me know haha

**Comment by rwbarkeriv** [comment]
nevermind i got it wait for new commit to merge

**Comment by rwbarkeriv** [comment]
all good!:)

**Pull request merged**
